name: Terraform Deploy

on:
  push:
    branches:
      - main
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::443370712526:role/bootcamp-cloud-terraform
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Inicializar Terraform
        run: terraform init

      - name: Planejar Terraform
        run: terraform plan

      - name: Aplicar Terraform
        run: terraform apply -auto-approve
