name: Deploy to Development

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      environment: 'dev'
      aws_region: 'us-east-2'
      role_arn: ${{ secrets.AWS_ROLE_ARN_OIDC }} 
