name: Teste AWS OIDC

on: push

permissions:
  id-token: write
  contents: read

jobs:
  test-aws-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/TerraformGitHubActionsRole
          aws-region: us-east-1

      - name: Testar AWS CLI
        run: aws sts get-caller-identity
